name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      # https://github.com/actions/checkout
    - name: checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        bazelisk build //src:cli
